on:
  push:
    branches:
      - main
      - demo
jobs:
  update:
    name: EAS Update
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20.15.0

      - name: Setup EAS
        uses: expo/expo-github-action@v8
        with:
          eas-version: latest
          token: ${{ secrets.EXPO_ACCESS_TOKEN }}

      - name: Install dependencies
        run: npm i

      - name: Commit update
        run: |
          if [ "${GITHUB_REF_NAME}" = "main" ]; then
            eas update --channel production --auto --non-interactive
          elif [ "${GITHUB_REF_NAME}" = "demo" ]; then
            eas update --channel demo --auto --non-interactive
          fi
        env:
          EXPO_PUBLIC_WEB_APP_URL: https://cool-cars-garage.co.uk
          EXPO_PUBLIC_API_URL: https://api.cool-cars-garage.co.uk
